export enum OP {
    ShowText = "ShowText",
    HideText = "HideText",
    ShowChioce = "ShowChoice",
    HideChioce = "HideChoice",
    PlayBGM = "PlayBGM",
    StopBGM = "StopBGM",
    PauseBGM = "PauseBGM",
    ResumeBGM = "ResumeBGM",
    PlayVoice = "PlayVoice",
    PlayBGS = "PlayBGS",
    PlaySE = "PlaySE",
    LoadScene = "LoadScene",
    Wait = "Wait",
    PlayEffect = "PlayEffect",
    StopEffect = "StopEffect",
    GotoTitleView = "GotoTitleView",
    ShowSubtitle = "ShowSubtitle",
    UpdateSubtitle = "UpdateSubtitle",
    HideSubtitle = "HideSubtitle",
    AnimateSubtitle = "AnimateSubtitle"
}
